### ISSUE TITLE
Ratings don't seem to appear?

### ISSUE THREAD

**Issue by akshaaatt** [pavi2410/PlayBadges#12]
Some apps don't show the ratings, can this be fixed?

Ex: https://github.com/metabrainz/musicbrainz-android

**Comment by pavi2410** [comment]
Ummm, I just checked the Play Store pages for a few apps including yours. I found that Musicbrainz app's page doesn't have a ratings section due to which the scraper didn't work.

![image](https://user-images.githubusercontent.com/28837746/146566058-4eec4fb1-5daf-4e42-8d3e-574d266aae8b.png)

Here's the whatsapp's page

![image](https://user-images.githubusercontent.com/28837746/146566141-0ac0e927-89fa-4c64-ac0e-69e7ff200586.png)

For once, I thought it's due to the policy change: https://android-developers.googleblog.com/2021/08/making-ratings-and-reviews-better-for.html But I guess that's not the case.

Could you confirm the same? I would say it's worth to contact Play Store support about the same.

**Comment by akshaaatt** [comment]
Hi @pavi2410! I actually have a few projects private and even they don't seem to show the ratings, given when things seem fine on the play store. Is there a minimum requirement of something like 50 ratings to show them here?

**Comment by akshaaatt** [comment]
I found more examples and none of the apps I have or now show the ratings. 
https://github.com/phw/PicardBarcodeScanner

**Comment by pavi2410** [comment]
> For once, I thought it's due to the policy change: https://android-developers.googleblog.com/2021/08/making-ratings-and-reviews-better-for.html But I guess that's not the case.

I can confirm that this is causing the trouble.

Case 1: https://play.google.com/store/apps/details?id=org.metabrainz.android&hl=en&gl=us
Case 2: https://play.google.com/store/apps/details?id=org.metabrainz.android (Region = India)

It happens to return the rating in the India region, but not for the US region, which the scraper library defaults to.

**Comment by pavi2410** [comment]
A solution which came in my mind is that I could detect the country from which the badge request is coming from, and fetch data for that country.

**Comment by akshaaatt** [comment]
Cool, did you try out the fix?

**Comment by pavi2410** [comment]
> Cool, did you try out the fix?
> 

Not yet. Later today, in the evening

**Comment by pavi2410** [comment]
Seems to work now

![image](https://user-images.githubusercontent.com/28837746/147215660-7f4009c4-0d30-4d56-b992-7fbeae8130c5.png)

Case 1: ![](https://PlayBadges.pavi2410.me/badge/ratings?id=org.metabrainz.android&no-cache)
Case 2: ![image](https://user-images.githubusercontent.com/28837746/147215674-cd01c2a0-34da-4a49-b5d3-7d47e780c396.png)

**Comment by akshaaatt** [comment]
Cool! Have you pushed this fix?

**Comment by pavi2410** [comment]
Yep! https://github.com/pavi2410/PlayBadges/commit/f3d54937fbc764fcb643e0344ba2f4a422355b77

And it's live too

**Comment by akshaaatt** [comment]
Should I make some changes to have the correct implementation be visible on  https://github.com/metabrainz/musicbrainz-android, or just wait?

**Comment by pavi2410** [comment]
Ideally, you don't need to make any changes. But you have to be wary of these things:
1. I enabled memorization of the requests for upto 24 hrs. This lowers the risk of IP ban from Play Store as a preventive measure.
2. Browser have store the badges in the cache storage, so you may have to wait until the cache is invalidated. Although I haven't added any headers for caching, I probably should add them to control the lifetime of the cache precisely.

**Comment by akshaaatt** [comment]
Cool, let me know when the changes start reflecting. Thanks
