### ISSUE TITLE
Ratings badge broken?

### ISSUE THREAD

**Issue by ErikBjare** [pavi2410/PlayBadges#25]
Hi there! Awesome repo, just what I was looking for.

However, I discovered that the ratings badge isn't working? It works when in issues/README and such (cached and served by GitHub), but if I open the link directly, I just get `0/5 (0)`.

![](https://PlayBadges.pavi2410.me/badge/ratings?id=net.activitywatch.android)

Downloads works as expected, though.

I'm in Sweden, so I suppose it *could* have something to do with this line?

https://github.com/pavi2410/PlayBadges/blob/e46b408e7c57a2e7bef20ae60352fc849a3e466f/src/index.ts#L97

~~I also notice that I can't see ratings on the Google Play Store website (weirdly). Perhaps they deprecated whichever API you are using?~~

Thanks again for the work you've done here!

**Comment by pavi2410** [comment]
Hi, I see that the badge is showing for me.

![image](https://github.com/pavi2410/PlayBadges/assets/28837746/6e8b9a3c-d853-4ce1-8d9a-818c907a9012)

And I tried checking the reviews badge for Whatsapp
```
https://PlayBadges.pavi2410.me/badge/ratings?id=com.whatsapp
```
which works as well.

Can you please check again?

**Comment by pavi2410** [comment]
> I'm in Sweden, so I suppose it _could_ have something to do with this line?

It could be possible that in Sweden, you have 0 ratings, whereas in the US, you have some ratings. Let me know if I should add a param to force it to default to a particular country.

**Comment by ErikBjare** [comment]
Aaah, so that's what it does! The download count seems non-specific to Sweden however.

Forcing the country to global/US would be great.

**Comment by pavi2410** [comment]
Done that! https://github.com/pavi2410/PlayBadges/commit/e5953d86db2d44b7896645e75ffb45cdb12f4bab

Please check the README

**Comment by ErikBjare** [comment]
That fixed it, thanks!

Badge proudly shown off at https://activitywatch.net/stats/
